/* 
 * The MIT License
 *
 * Copyright 2016 Tonmoay Deb <tonmoay.deb@northsouth.edu>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package mysynopsis;

import java.awt.CardLayout;
import java.awt.Desktop;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URI;
import java.net.URISyntaxException;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.HTMLEditor;

/**
 *
 * @author Tonmoay Deb
 */
public class MotherFrame extends Variables {

    /**
     * Creates new form MotherFrame
     */
    static JFrame mframe;
    HTMLEditor bioInfo, eduInfo, profInfo, awardsInfo;
    
    public MotherFrame() {
        initComponents();
        mframe = this;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Previous = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        Last = new javax.swing.JButton();
        First = new javax.swing.JButton();
        SaveAll = new javax.swing.JButton();
        Export = new javax.swing.JButton();
        Preview = new javax.swing.JButton();
        Upload = new javax.swing.JButton();
        personalInfoButton = new javax.swing.JButton();
        pictureButton = new javax.swing.JButton();
        universityInfoButton = new javax.swing.JButton();
        eduInfoButton = new javax.swing.JButton();
        professionaExperienceButton = new javax.swing.JButton();
        biographyButton = new javax.swing.JButton();
        awardsButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        panelBasic = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        initialField = new javax.swing.JTextField(initial);
        emailfield = new javax.swing.JTextField(email);
        phonefield = new javax.swing.JTextField(phone);
        jLabel8 = new javax.swing.JLabel();
        resumefield = new javax.swing.JTextField(resumelink);
        nameField = new javax.swing.JTextField(name);
        jLabel12 = new javax.swing.JLabel();
        panelBiography = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        panelImage = new javax.swing.JPanel();
        imageup = new javax.swing.JLabel();
        imageupbtn = new javax.swing.JButton();
        panelUnivInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        desigfield = new javax.swing.JTextField(designation);
        jLabel2 = new javax.swing.JLabel();
        deptfield = new javax.swing.JTextField(dept);
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        oroomfield = new javax.swing.JTextField(office);
        ohoursfield = new javax.swing.JTextField(officehours);
        univaddress = new javax.swing.JTextField(universityAddress);
        jLabel13 = new javax.swing.JLabel();
        univfield = new javax.swing.JTextField(university);
        panelEduInfo = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        panelProfInfo = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        panelAwards = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        aboutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Synopsis");
        setResizable(false);

        Previous.setText("Previous");
        Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousActionPerformed(evt);
            }
        });

        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Last.setText("Last");
        Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastActionPerformed(evt);
            }
        });

        First.setText("First");
        First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstActionPerformed(evt);
            }
        });

        SaveAll.setText("Save All");
        SaveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAllActionPerformed(evt);
            }
        });

        Export.setText("Export as HTML");
        Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportActionPerformed(evt);
            }
        });

        Preview.setText("Preview Website");
        Preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviewActionPerformed(evt);
            }
        });

        Upload.setText("Upload to FTP");
        Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadActionPerformed(evt);
            }
        });

        personalInfoButton.setText("PERSONAL INFORMATION");
        personalInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalInfoButtonActionPerformed(evt);
            }
        });

        pictureButton.setText("PICTURE");
        pictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pictureButtonActionPerformed(evt);
            }
        });

        universityInfoButton.setText("DESIGNATION AT UNIVERSITY");
        universityInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universityInfoButtonActionPerformed(evt);
            }
        });

        eduInfoButton.setText("EDUCATIONAL INFORMATION");
        eduInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduInfoButtonActionPerformed(evt);
            }
        });

        professionaExperienceButton.setText("PROFESSIONAL EXPERIENCE");
        professionaExperienceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professionaExperienceButtonActionPerformed(evt);
            }
        });

        biographyButton.setText("BIOGRAPHY");
        biographyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biographyButtonActionPerformed(evt);
            }
        });

        awardsButton.setText("ACHIEVED AWARDS");
        awardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awardsButtonActionPerformed(evt);
            }
        });

        mainPanel.setLayout(new java.awt.CardLayout());

        panelBasic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Faculty Initial:");
        panelBasic.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 40));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Email Address:");
        panelBasic.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 110, 40));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Resume Link:");
        panelBasic.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, 40));

        initialField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialFieldActionPerformed(evt);
            }
        });
        panelBasic.add(initialField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 200, 30));
        panelBasic.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 200, 30));

        phonefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonefieldActionPerformed(evt);
            }
        });
        panelBasic.add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 200, 30));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Phone Number:");
        panelBasic.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 40));
        panelBasic.add(resumefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 380, 30));

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        panelBasic.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 200, 30));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setText("Full Name:");
        panelBasic.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 40));

        mainPanel.add(panelBasic, "panelBasic");

        panelBiography.setLayout(new java.awt.BorderLayout());
        final JFXPanel bioPanel = new JFXPanel();

        panelBiography.add(bioPanel);
        // Code of sub-components and layout - not shown here
        Platform.runLater(() -> {
            bioInfo = new HTMLEditor();
            Scene bioScene = new Scene(bioInfo);
            bioInfo.setPrefHeight(245);
            bioInfo.setPrefWidth(245);
            bioInfo.setHtmlText(biog);
            bioPanel.setScene(bioScene);
        });

        jLabel22.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel22.setText("Biography:");
        panelBiography.add(jLabel22, java.awt.BorderLayout.PAGE_START);

        mainPanel.add(panelBiography, "panelBiography");

        panelImage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try {
            imageup.setIcon(new javax.swing.ImageIcon(ImageProcess.toBufferedImage()));
        }

        catch(Exception x) {

        }
        panelImage.add(imageup, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 310, 260));

        imageupbtn.setText("Upload Image");
        imageupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageupbtnActionPerformed(evt);
            }
        });
        panelImage.add(imageupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 110, 40));

        mainPanel.add(panelImage, "panelImage");

        panelUnivInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        panelUnivInfo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 30));
        panelUnivInfo.add(desigfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 270, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Designation:");
        panelUnivInfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));
        panelUnivInfo.add(deptfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 270, 30));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Department:");
        panelUnivInfo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("University Address:");
        panelUnivInfo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 30));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setText("Office Room:");
        panelUnivInfo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Office Hours:");
        panelUnivInfo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));
        panelUnivInfo.add(oroomfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 270, 30));
        panelUnivInfo.add(ohoursfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 270, 30));

        univaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                univaddressActionPerformed(evt);
            }
        });
        panelUnivInfo.add(univaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 370, 30));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setText("University Name:");
        panelUnivInfo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 30));

        univfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                univfieldActionPerformed(evt);
            }
        });
        panelUnivInfo.add(univfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 270, 30));

        mainPanel.add(panelUnivInfo, "panelUnivInfo");

        panelEduInfo.setLayout(new java.awt.BorderLayout());
        final JFXPanel eduPanel = new JFXPanel();

        panelEduInfo.add(eduPanel);
        // Code of sub-components and layout - not shown here
        Platform.runLater(() -> {
            eduInfo = new HTMLEditor();
            Scene eduScene = new Scene(eduInfo);
            eduInfo.setPrefHeight(245);
            eduInfo.setPrefWidth(245);
            eduInfo.setHtmlText(education);
            eduPanel.setScene(eduScene);
        });

        jLabel23.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel23.setText("Educational Information");
        panelEduInfo.add(jLabel23, java.awt.BorderLayout.PAGE_START);

        mainPanel.add(panelEduInfo, "panelEduInfo");

        final JFXPanel profPanel = new JFXPanel();
        panelProfInfo.setLayout(new java.awt.BorderLayout());
        panelProfInfo.add(profPanel);

        jLabel21.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel21.setText("Your Professional Experience ( Keep Blank if None )");
        panelProfInfo.add(jLabel21, java.awt.BorderLayout.PAGE_START);

        Platform.runLater(() -> {
            profInfo = new HTMLEditor();
            Scene profScene = new Scene(profInfo);
            profInfo.setPrefHeight(245);
            profInfo.setPrefWidth(245);
            profInfo.setHtmlText(professional);
            profPanel.setScene(profScene);
        });

        mainPanel.add(panelProfInfo, "panelProfInfo");
        panelProfInfo.getAccessibleContext().setAccessibleName("");

        panelAwards.setLayout(new java.awt.BorderLayout());
        final JFXPanel awardsPanel = new JFXPanel();

        panelAwards.add(awardsPanel);
        // Code of sub-components and layout - not shown here
        Platform.runLater(() -> {
            awardsInfo = new HTMLEditor();
            Scene awardsScene = new Scene(awardsInfo);
            awardsInfo.setPrefHeight(245);
            awardsInfo.setPrefWidth(245);
            awardsInfo.setHtmlText(awards);
            awardsPanel.setScene(awardsScene);
        });

        jLabel24.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel24.setText("Awards Information ( Keep Blank if None )");
        panelAwards.add(jLabel24, java.awt.BorderLayout.PAGE_START);

        mainPanel.add(panelAwards, "panelAwards");

        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eduInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(universityInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(personalInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pictureButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(professionaExperienceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(biographyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(awardsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(First, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Previous, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Last, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Export)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Preview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Upload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aboutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(personalInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(biographyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pictureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(universityInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eduInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(professionaExperienceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(awardsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(Previous, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(First, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Next)
                    .addComponent(Last)
                    .addComponent(SaveAll)
                    .addComponent(Export)
                    .addComponent(Preview)
                    .addComponent(Upload)
                    .addComponent(aboutButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.previous(mainPanel);
    }//GEN-LAST:event_PreviousActionPerformed

    private void pictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pictureButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "panelImage");
    }//GEN-LAST:event_pictureButtonActionPerformed

    private void initialFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialFieldActionPerformed

    private void universityInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universityInfoButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "panelUnivInfo");
    }//GEN-LAST:event_universityInfoButtonActionPerformed

    private void personalInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalInfoButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "panelBasic");
    }//GEN-LAST:event_personalInfoButtonActionPerformed

    private void univaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_univaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_univaddressActionPerformed

    private void FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.first(mainPanel);
    }//GEN-LAST:event_FirstActionPerformed

    private void LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.last(mainPanel);
    }//GEN-LAST:event_LastActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.next(mainPanel);
    }//GEN-LAST:event_NextActionPerformed

    
    private void univfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_univfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_univfieldActionPerformed

    private void eduInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduInfoButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "panelEduInfo");
    }//GEN-LAST:event_eduInfoButtonActionPerformed

    private void imageupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageupbtnActionPerformed
        // TODO add your handling code here:
        JFileChooser choose = new JFileChooser();
        
        choose.showOpenDialog(null);
        
        String path = choose.getSelectedFile().getPath();
        String filename=choose.getSelectedFile().getName();
        imgExtension = filename.substring(filename.lastIndexOf("."),filename.length());
        imgExtension = imgExtension.replace(".", "");
        
        
        try {
            imgString = ImageProcess.toImageString(path);
        } catch (IOException ex) {
            Logger.getLogger(MotherFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //    System.out.println(path);
        imageup.setIcon(new javax.swing.ImageIcon(path));
    }//GEN-LAST:event_imageupbtnActionPerformed

    private void PreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviewActionPerformed
        // TODO add your handling code here:
        PreviewPage.mySitePreview();
    }//GEN-LAST:event_PreviewActionPerformed

    private void SaveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAllActionPerformed
        // TODO add your handling code here:
        
        //Get Values from TextFields and set
        
        name = nameField.getText();
        initial = initialField.getText();
        email = emailfield.getText();
        phone = phonefield.getText();
        resumelink = resumefield.getText();
        
        biog = bioInfo.getHtmlText();
        biog = biog.replace("<html dir=\"ltr\"><head></head>","");
        biog = biog.replace("<body contenteditable=\"true\">","");
        biog = biog.replace("</body></html>","");
        
        designation = desigfield.getText();
        dept = deptfield.getText();
        office = oroomfield.getText();
        officehours = ohoursfield.getText();
        university = univfield.getText();
        universityAddress = univaddress.getText();
        /*educ[0] = highfield.getText();
        educ[1] = highdufield.getText();
        educ[2] = collegefield.getText();
        educ[3] = collegedufield.getText();
        educ[4] = undergradfield.getText();
        educ[5] = undergraddufield.getText();
        educ[6] = gradfield.getText();
        educ[7] = graddurationfield.getText();*/
        
        education = eduInfo.getHtmlText();
        education = education.replace("<html dir=\"ltr\"><head></head>","");
        education = education.replace("<body contenteditable=\"true\">","");
        education = education.replace("</body></html>","");
        
        professional = profInfo.getHtmlText();
        professional = professional.replace("<html dir=\"ltr\"><head></head>","");
        professional = professional.replace("<body contenteditable=\"true\">","");
        professional = professional.replace("</body></html>","");
        
        awards = awardsInfo.getHtmlText();
        awards = awards.replace("<html dir=\"ltr\"><head></head>","");
        awards = awards.replace("<body contenteditable=\"true\">","");
        awards = awards.replace("</body></html>","");
        
      //  System.out.println(professional);
        
        EventQueue.invokeLater(() -> {
            try {
                JSONWriter.writeData();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,"Some Error Occured. Please Try Again.");
            }
        });
        JOptionPane.showMessageDialog(this,"Saved Successfully.");
    }//GEN-LAST:event_SaveAllActionPerformed

    private void ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportActionPerformed

        
        // TODO add your handling code here:
        
        //Get Values from TextFields and set
        name = nameField.getText();
        initial = initialField.getText();
        email = emailfield.getText();
        phone = phonefield.getText();
        resumelink = resumefield.getText();
        
        biog = bioInfo.getHtmlText();
        biog = biog.replace("<html dir=\"ltr\"><head></head>","");
        biog = biog.replace("<body contenteditable=\"true\">","");
        biog = biog.replace("</body></html>","");
        
        designation = desigfield.getText();
        dept = deptfield.getText();
        office = oroomfield.getText();
        officehours = ohoursfield.getText();
        university = univfield.getText();
        universityAddress = univaddress.getText();
        
        /* educ[0] = highfield.getText();
        educ[1] = highdufield.getText();
        educ[2] = collegefield.getText();
        educ[3] = collegedufield.getText();
        educ[4] = undergradfield.getText();
        educ[5] = undergraddufield.getText();
        educ[6] = gradfield.getText();
        educ[7] = graddurationfield.getText(); */
        
        education = eduInfo.getHtmlText();
        education = education.replace("<html dir=\"ltr\"><head></head>","");
        education = education.replace("<body contenteditable=\"true\">","");
        education = education.replace("</body></html>","");
        
        professional = profInfo.getHtmlText();
        professional = professional.replace("<html dir=\"ltr\"><head></head>","");
        professional = professional.replace("<body contenteditable=\"true\">","");
        professional = professional.replace("</body></html>","");
        
        awards = awardsInfo.getHtmlText();
        awards = awards.replace("<html dir=\"ltr\"><head></head>","");
        awards = awards.replace("<body contenteditable=\"true\">","");
        awards = awards.replace("</body></html>","");
    
        EventQueue.invokeLater(() -> {
            try {
                
                JOptionPane.showMessageDialog(this,HTMLWriter.writeHTML());
            } catch (IOException ex) {
                Logger.getLogger(MotherFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
    }//GEN-LAST:event_ExportActionPerformed

    private void UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadActionPerformed
        try {
            // TODO add your handling code here:
            FTPUploader.display();
        } catch (IOException ex) {
            Logger.getLogger(MotherFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UploadActionPerformed

    private void professionaExperienceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professionaExperienceButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "panelProfInfo");
    }//GEN-LAST:event_professionaExperienceButtonActionPerformed

    private void awardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awardsButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "panelAwards");
    }//GEN-LAST:event_awardsButtonActionPerformed

    private void biographyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biographyButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "panelBiography");
    }//GEN-LAST:event_biographyButtonActionPerformed

    private void phonefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonefieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        // TODO add your handling code here:
        
        String msg = "<html> <br> <b> My Synopsis </b> - A Simple Faculty Profile Builder <br> <br> A CSE215 ( Object Oriented Programming ) Project, North South University <br> <br> Copyright © 2016 Tonmoay Deb ( tonmoay.deb@northsouth.edu ) <br>  <br> Licensed Under MIT License <br> <br> GitHub Link: <a href=\"https://github.com/tonmoay/My-Synopsis\"> https://github.com/tonmoay/My-Synopsis </a></html>";
        JLabel label = new JLabel(msg);
        label.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            
            try {
                Desktop.getDesktop().browse(new URI("https://github.com/tonmoay/My-Synopsis"));
            } catch (URISyntaxException | IOException ex) {
               JOptionPane.showMessageDialog(MotherFrame.mframe,"Can't Open URL");
            }
        }
        });
   //     label.setFont(new Font("serif", Font.PLAIN, 14));
        JOptionPane.showConfirmDialog(this, label,"About - My Synopsis",JOptionPane.PLAIN_MESSAGE); 
        
        //JOptionPane.showMessageDialog(this,"My Synopsis - A Simple Faculty Profile Builder\nA CSE215 ( Object Oriented Programming ) Project\nNorth South University\nOpen Source Project, Hosted in GitHub\nCopyright © 2016 Tonmoay Deb ( tonmoay.deb@northsouth.edu )\nLicensed Under MIT License\nGitHub Link: https://github.com/tonmoay/My-Synopsis");
        
    }//GEN-LAST:event_aboutButtonActionPerformed

   
    /*public static void main(String args[]) {*/
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /*try {
    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Nimbus".equals(info.getName())) {
    javax.swing.UIManager.setLookAndFeel(info.getClassName());
    break;
    }
    }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
    java.util.logging.Logger.getLogger(MotherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }*/
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        /*    java.awt.EventQueue.invokeLater(() -> {
        new MotherFrame().setVisible(true);
        });
        }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Export;
    private javax.swing.JButton First;
    private javax.swing.JButton Last;
    private javax.swing.JButton Next;
    private javax.swing.JButton Preview;
    private javax.swing.JButton Previous;
    private javax.swing.JButton SaveAll;
    private javax.swing.JButton Upload;
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton awardsButton;
    private javax.swing.JButton biographyButton;
    private javax.swing.JTextField deptfield;
    private javax.swing.JTextField desigfield;
    private javax.swing.JButton eduInfoButton;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel imageup;
    private javax.swing.JButton imageupbtn;
    private javax.swing.JTextField initialField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField ohoursfield;
    private javax.swing.JTextField oroomfield;
    private javax.swing.JPanel panelAwards;
    private javax.swing.JPanel panelBasic;
    private javax.swing.JPanel panelBiography;
    private javax.swing.JPanel panelEduInfo;
    private javax.swing.JPanel panelImage;
    private javax.swing.JPanel panelProfInfo;
    private javax.swing.JPanel panelUnivInfo;
    private javax.swing.JButton personalInfoButton;
    private javax.swing.JTextField phonefield;
    private javax.swing.JButton pictureButton;
    private javax.swing.JButton professionaExperienceButton;
    private javax.swing.JTextField resumefield;
    private javax.swing.JTextField univaddress;
    private javax.swing.JButton universityInfoButton;
    private javax.swing.JTextField univfield;
    // End of variables declaration//GEN-END:variables
}
