/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysynopsis;

import java.awt.CardLayout;
import javax.swing.*;


/**
 *
 * @author Personal
 */
public class MotherFrame extends javax.swing.JFrame {

    /**
     * Creates new form MotherFrame
     */
    public MotherFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Previous = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        Last = new javax.swing.JButton();
        First = new javax.swing.JButton();
        SaveAll = new javax.swing.JButton();
        Export = new javax.swing.JButton();
        Preview = new javax.swing.JButton();
        Upload = new javax.swing.JButton();
        set_one = new javax.swing.JButton();
        set_two = new javax.swing.JButton();
        set_three = new javax.swing.JButton();
        set_five = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        panelOne = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        phonefield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        biofield = new javax.swing.JTextArea();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel8 = new javax.swing.JLabel();
        resumefield = new javax.swing.JTextField();
        panelTwo = new javax.swing.JPanel();
        imageup = new javax.swing.JLabel();
        imageupbtn = new javax.swing.JButton();
        panelThree = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        desigfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        deptfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        oroomfield = new javax.swing.JTextField();
        ohoursfield = new javax.swing.JTextField();
        univfield = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        univfield1 = new javax.swing.JTextField();
        panelFour = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        graddurationfield = new javax.swing.JTextField();
        highfield = new javax.swing.JTextField();
        highdufield = new javax.swing.JTextField();
        collegefield = new javax.swing.JTextField();
        collegedufield = new javax.swing.JTextField();
        undergradfield = new javax.swing.JTextField();
        undergraddufield = new javax.swing.JTextField();
        gradfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Previous.setText("Previous");
        Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousActionPerformed(evt);
            }
        });

        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Last.setText("Last");
        Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastActionPerformed(evt);
            }
        });

        First.setText("First");
        First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstActionPerformed(evt);
            }
        });

        SaveAll.setText("Save All");

        Export.setText("Export as HTML");

        Preview.setText("Preview Website");

        Upload.setText("Upload to FTP");

        set_one.setText("PERSONAL INFORMATION");
        set_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_oneActionPerformed(evt);
            }
        });

        set_two.setText("PICTURE");
        set_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_twoActionPerformed(evt);
            }
        });

        set_three.setText("DESIGNATION AT UNIVERSITY");
        set_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_threeActionPerformed(evt);
            }
        });

        set_five.setText("EDUCATIONAL INFORMATION");
        set_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_fiveActionPerformed(evt);
            }
        });

        mainPanel.setLayout(new java.awt.CardLayout());

        panelOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Biography:");
        panelOne.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 40));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Name:");
        panelOne.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 40));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Email:");
        panelOne.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 40));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Resume Link:");
        panelOne.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, 40));

        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        panelOne.add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 200, 30));
        panelOne.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, 30));
        panelOne.add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 200, 30));

        biofield.setColumns(20);
        biofield.setRows(5);
        jScrollPane1.setViewportView(biofield);

        panelOne.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 400, 150));
        panelOne.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Phone Number:");
        panelOne.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 40));
        panelOne.add(resumefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 400, 30));

        mainPanel.add(panelOne, "panelOne");

        panelTwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelTwo.add(imageup, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 310, 260));

        imageupbtn.setText("Upload Image");
        imageupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageupbtnActionPerformed(evt);
            }
        });
        panelTwo.add(imageupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 110, 40));

        mainPanel.add(panelTwo, "panelTwo");

        panelThree.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        panelThree.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 30));
        panelThree.add(desigfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 270, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Designation:");
        panelThree.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));
        panelThree.add(deptfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 270, 30));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Department:");
        panelThree.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("University Address:");
        panelThree.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 30));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setText("Office Room:");
        panelThree.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Office Hours:");
        panelThree.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));
        panelThree.add(oroomfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 270, 30));
        panelThree.add(ohoursfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 270, 30));

        univfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                univfieldActionPerformed(evt);
            }
        });
        panelThree.add(univfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 370, 30));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setText("University Name:");
        panelThree.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 30));

        univfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                univfield1ActionPerformed(evt);
            }
        });
        panelThree.add(univfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 270, 30));

        mainPanel.add(panelThree, "panelThree");

        panelFour.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setText("Duration:");
        panelFour.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 210, 40));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setText("High School:");
        panelFour.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel15.setText("Duration:");
        panelFour.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 40));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setText("College Name:");
        panelFour.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 40));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel17.setText("Duration:");
        panelFour.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 40));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setText("Undergrad University:");
        panelFour.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, 40));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel19.setText("Duration:");
        panelFour.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, 40));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel20.setText("Graduate University");
        panelFour.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 210, 40));
        panelFour.add(graddurationfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 140, 30));
        panelFour.add(highfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 290, 30));
        panelFour.add(highdufield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 140, 30));
        panelFour.add(collegefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 290, 30));
        panelFour.add(collegedufield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 140, 30));
        panelFour.add(undergradfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 290, 30));
        panelFour.add(undergraddufield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 140, 30));
        panelFour.add(gradfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 290, 30));

        mainPanel.add(panelFour, "panelFour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(set_five, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(set_three, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(set_one, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(set_two, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(First)
                .addGap(18, 18, 18)
                .addComponent(Previous)
                .addGap(18, 18, 18)
                .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Last, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SaveAll)
                .addGap(18, 18, 18)
                .addComponent(Export)
                .addGap(18, 18, 18)
                .addComponent(Preview)
                .addGap(18, 18, 18)
                .addComponent(Upload)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(set_one, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(set_two, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(set_three, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(set_five, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Previous)
                    .addComponent(Next)
                    .addComponent(Last)
                    .addComponent(First)
                    .addComponent(SaveAll)
                    .addComponent(Export)
                    .addComponent(Preview)
                    .addComponent(Upload))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.previous(mainPanel);
    }//GEN-LAST:event_PreviousActionPerformed

    private void set_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_twoActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "panelTwo");
    }//GEN-LAST:event_set_twoActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private void set_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_threeActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "panelThree");
    }//GEN-LAST:event_set_threeActionPerformed

    private void set_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_oneActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "panelOne");
    }//GEN-LAST:event_set_oneActionPerformed

    private void univfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_univfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_univfieldActionPerformed

    private void FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.first(mainPanel);
    }//GEN-LAST:event_FirstActionPerformed

    private void LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.last(mainPanel);
    }//GEN-LAST:event_LastActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.next(mainPanel);
    }//GEN-LAST:event_NextActionPerformed

    private void univfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_univfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_univfield1ActionPerformed

    private void set_fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_fiveActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "panelFour");
    }//GEN-LAST:event_set_fiveActionPerformed

    private void imageupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageupbtnActionPerformed
        // TODO add your handling code here:
        JFileChooser choose = new JFileChooser();
        
        choose.showOpenDialog(null);
        
        String path = choose.getSelectedFile().getPath();
    //    System.out.println(path); 
        imageup.setIcon(new javax.swing.ImageIcon(path));
    }//GEN-LAST:event_imageupbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MotherFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Export;
    private javax.swing.JButton First;
    private javax.swing.JButton Last;
    private javax.swing.JButton Next;
    private javax.swing.JButton Preview;
    private javax.swing.JButton Previous;
    private javax.swing.JButton SaveAll;
    private javax.swing.JButton Upload;
    private javax.swing.JTextArea biofield;
    private javax.swing.JTextField collegedufield;
    private javax.swing.JTextField collegefield;
    private javax.swing.JTextField deptfield;
    private javax.swing.JTextField desigfield;
    private javax.swing.JTextField emailfield;
    private javax.swing.JTextField graddurationfield;
    private javax.swing.JTextField gradfield;
    private javax.swing.JTextField highdufield;
    private javax.swing.JTextField highfield;
    private javax.swing.JLabel imageup;
    private javax.swing.JButton imageupbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField ohoursfield;
    private javax.swing.JTextField oroomfield;
    private javax.swing.JPanel panelFour;
    private javax.swing.JPanel panelOne;
    private javax.swing.JPanel panelThree;
    private javax.swing.JPanel panelTwo;
    private javax.swing.JTextField phonefield;
    private javax.swing.JTextField resumefield;
    private javax.swing.JButton set_five;
    private javax.swing.JButton set_one;
    private javax.swing.JButton set_three;
    private javax.swing.JButton set_two;
    private javax.swing.JTextField undergraddufield;
    private javax.swing.JTextField undergradfield;
    private javax.swing.JTextField univfield;
    private javax.swing.JTextField univfield1;
    // End of variables declaration//GEN-END:variables
}
