/* 
 * The MIT License
 *
 * Copyright 2016 Tonmoay Deb <tonmoay.deb@northsouth.edu>.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package mysynopsis;

import java.awt.Dimension;
import java.io.File;
import java.net.MalformedURLException;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javax.swing.JOptionPane;
import javafx.scene.web.WebView;
import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 *
 * @author Tonmoay Deb
 * 
 * This Class will do preview of a website which has been generated by system
 */
public abstract class PreviewPage {
    
    /*public static void mySitePreview() throws FileNotFoundException, IOException {
    JFrame preview = new JFrame("Preview My Site - My Synopsis");
    JFXPanel jfxPanel = new JFXPanel();
    preview.add(jfxPanel);
    
    Platform.runLater(() -> {
    WebView webView = new WebView();
    
    jfxPanel.setScene(new Scene(webView));
    
    File f = new File("index.html");
    
    try {
    
    webView.getEngine().load(f.toURI().toURL().toString());
    //   System.out.println(f.toURI().toURL().toString());
    }
    catch(MalformedURLException e) {
    
    JOptionPane.showMessageDialog(preview,"Error. Please Try Again");
    }
    });
    
    preview.setDefaultCloseOperation( JFrame.DISPOSE_ON_CLOSE );
    preview.setSize(800,600);
    preview.setVisible(true);
    }*/
    
    
    public static void mySitePreview() {

    JPanel myPanel = new JPanel();

    final JFXPanel fxPanel = new JFXPanel(); //JavaFX has been used here.

    myPanel.setLayout(new java.awt.BorderLayout());
    myPanel.add(fxPanel);

    Platform.runLater(() -> {
        WebView webView = new WebView();
        fxPanel.setScene(new Scene(webView));
        
        try { //File Export
            
            File f = new File("index.html");
            webView.getEngine().load(f.toURI().toURL().toString());
         //   System.out.println(f.toURI().toURL().toString());
        }
        catch(MalformedURLException e) {
            
            JOptionPane.showMessageDialog(MotherFrame.mframe,"Something Went Wrong. Please restart the applicaton.");
        }
    });
    
        // myPanel.setMinimumSize(new Dimension(1800,1600));
       // UIManager.put("OptionPane.minimumSize",new Dimension(800,600)); 

       // JOptionPane.showConfirmDialog(null, myPanel, "Website Preview - My Synopsis",  JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE);
        
       // UIManager.put("OptionPane.minimumSize",new Dimension(200,200)); 
       
       
       
       JOptionPane pane = new JOptionPane(myPanel);
       JDialog dialog = pane.createDialog(MotherFrame.mframe, "Website Preview - My Synopsis");
       dialog.setSize(new Dimension(800,600));
       dialog.setVisible(true);
}
    
}